[tools]
rust = "latest"
usage = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-edit" = "latest"

[tasks.init]
depends = "init:*"

[tasks."init:pre-commit"]
hide = true
sources = []
outputs = [".git/hooks/pre-commit"]
run = "mise generate pre-commit --write"

[tasks.changelog-md]
run = "cargo run -- --changelog CHANGELOG.yml"

[tasks.build]
run = "cargo build"

[tasks."build:release"]
run = "cargo build --release"

[tasks.format]
run = "cargo fmt"

[tasks.lint]
depends = "lint:**"

[tasks."lint:format"]
run = "cargo fmt --check"

[tasks."lint:clippy"]
run = "cargo clippy"

[tasks.test]
run = "cargo nextest run"

[tasks.pre-commit]
depends = ["lint", "test", "changelog:**"]

[tasks."changelog:render"]
run = "cargo run -- --changelog CHANGELOG.yml render"

[tasks."changelog:convert:toml"]
run = "cargo run -- --changelog CHANGELOG.yml convert --force --format toml"

[tasks."changelog:convert:json"]
run = "cargo run -- --changelog CHANGELOG.yml convert --force --format json"

[tasks.do-release]
run = [
    'cargo set-version {{arg(name="version")}}',
    'cargo run -- --changelog CHANGELOG.yml release {{arg(name="version")}} {{arg(name="description")}}',
    'mise run pre-commit',
    'echo git commit -am "Release {{arg(name="version")}}: {{arg(name="description")}}"',
    'echo git tag -a "{{arg(name="version")}}" -m {{arg(name="description")}}',
]
