# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: changelog-md:render
        name: "changelog-md render"
        language: system
        pass_filenames: false
        entry: cargo run -- --changelog CHANGELOG.yml render

      - id: changelog-md:convert:toml
        name: "changelog-md convert source yml to toml"
        language: system
        pass_filenames: false
        entry: cargo run -- --changelog CHANGELOG.yml convert --force --format toml

      - id: changelog-md:convert:json
        name: "changelog-md convert source yml to json"
        language: system
        pass_filenames: false
        entry: cargo run -- --changelog CHANGELOG.yml convert --force --format json
