title = "changelog-md"
description = """
All notable changes to this project will be documented in this file.

The format is derived from [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
repository = "https://github.com/kageurufu/changelog-md"

[unreleased]

[versions."1.1.2"]
tag = "1.1.2"
date = "2025-03-20"
description = "'Minor release, cleaning up some defaults'"
added = [
    "Attempt to find the current path's git remote url during init",
    "`yank` command to mark a version as yanked",
]
changed = [
    "Don't write null descriptions or yank reasons",
    "Use mise for build tools, task management, and pre-commit hooks",
    '''Don't write a fake version for a default changelog, instead add an unreleased "added - started using changelog-md"''',
]
fixed = ["Error when attempting to release the same version twice"]

[versions."1.1.1"]
tag = "1.1.1"
date = "2025-02-25"
description = "Documentation update"
added = ["documentation for all public members"]
fixed = ["Add repository, keywords, and categories to Cargo.toml"]

[versions."1.1.0"]
tag = "1.1.0"
date = "2025-02-25"
description = "First release made through `changelog-md release` 🎉"
added = [
    "`changelog-md add [added|changed|deprecated|removed|fixed|security] [description]`",
    "`changelog-md release [--tag=] [--date=] <VERSION> [DESCRIPTION]`",
]
changed = [
    "Markdown formatting adjustments, mostly fixing newlines",
    "Moved revision URLs to a `# Revisions` section",
]
fixed = [
    "Changelog::from_path now accepts `impl Into<std::path::PathBuf>`",
    "Add help string to `changelog-md release`",
    "`init` default value for `--format` was invalid",
    "accept `--format yml` as an alias for yaml",
    "Use pretty toml rendering",
    "Switch from deprecated serde_yaml to serde_yml",
    "Add tests for all cli functions",
    "Fix git urls, tag comparison was reversed",
]

[versions."1.0.0"]
tag = "1.0.0"
date = "2025-02-24"
description = """
Initial release, including the 1.0 Schema specification
"""
